services:
  dingdong:
    image: hexsean/dingdong:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - path: .env
        required: false
    tty: true
    stdin_open: true
